# Generated by Django 2.0.5 on 2019-04-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanapp', '0003_auto_20190407_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='shop_address',
            field=models.CharField(default=1, max_length=300, verbose_name='店舗住所'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='shop_name',
            field=models.CharField(default=1, max_length=200, verbose_name='店舗名'),
            preserve_default=False,
        ),
    ]
