# Generated by Django 2.0.5 on 2019-04-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanapp', '0004_auto_20190408_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image_url',
            field=models.CharField(blank=True, max_length=300, verbose_name='画像１URL'),
        ),
        migrations.AddField(
            model_name='review',
            name='shop_kana',
            field=models.CharField(default=1, max_length=400, verbose_name='店舗名カナ'),
            preserve_default=False,
        ),
    ]
